### ISSUE TITLE
大佬你好，

### ISSUE THREAD

**Issue by rianjskis** [jerry-dudu16/Actions-OpenWrt#1]
请问复刻你的 openwrt_Build仓库编译r2s除了更换.config文件还需要改动吗😄，用原作者的老是编译成他内置默认的.config内容了

**Comment by jerry-dudu16** [comment]
一般不用，但是还是建议你可以对比一下原作者的，根据你自身的需求二次调整

**Comment by rianjskis** [comment]
> 一般不用，但是还是建议你可以对比一下原作者的，根据你自身的需求二次调整

试了好几次还是失败，哈哈哈，整不会了
